apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"calico-cni-plugin"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"calico-cni-plugin"},"subjects":[{"kind":"ServiceAccount","name":"calico-cni-plugin","namespace":"kube-system"}]}
  creationTimestamp: "2024-09-16T19:42:41Z"
  name: calico-cni-plugin
  resourceVersion: "24845061"
  uid: 34f699a2-235b-47b4-be0d-b1310738cbaa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-cni-plugin
subjects:
- kind: ServiceAccount
  name: calico-cni-plugin
  namespace: kube-system
